<?
require("config.php");
require("valid.inc.php");
require('vendor/autoload.php');
$editQuery=$_GET['e'];
if(strlen($editQuery)!=0)
{    
    $sqlQuery="SELECT * FROM members  WHERE uid='$editQuery'";  
    $pickQuery=mysqli_query($CCIHCon,$sqlQuery)or die("Unable connect to the table");
    $rsmember=mysqli_fetch_array($pickQuery); 
}

$delQuery=$_GET['d'];
if(strlen($delQuery)!=0)
{    
    $delQuery="delete FROM members  WHERE uid='$delQuery'";  
    mysqli_query($CCIHCon,$delQuery)or die("Unable connect to the table");
        $msg="The details has been deleted successfully!";

}
if (isset($_POST['resetpwd'])) {
    $eid=$_POST['eid'];
    sendEmail($eid);  
    $msg="Successful! The new password link was sent to the registered email id";
}


if (isset($_POST['sub'])) {
    $uid=$_POST['uid'];
    $uname = str_replace("'", '-', $_POST['uname']); 
    $Design = str_replace("'", '-', $_POST['Design']);  
    $centreName=explode("-",$_POST['centreName']);
    $eid=$_POST['eid'];
    $uadd = str_replace("'", '-', $_POST['uadd']);
    $ucontact = $_POST['ucontact'];
    $ufax = $_POST['ufax'];
    $prev = $_POST['prev'];
    $sacc = $_POST['sacc'];

    if(strlen($uname)==0 ){

        $error ="Specify, name of the user"."<br/>";
        $errval = true;
    }
    if(strlen($centreName[0])==0 ){

        $error ="Specify, name of the center"."<br/>";;
        $errval = true;
    }
    if(strlen($eid)==0 ){

        $error ="Specify, email id"."<br/>";;
        $errval = true;
    }

    if(strlen($prev)==0 ){

        $error ="Specify, user's previlege"."<br/>";;
        $errval = true;
    }


    if ( $errval != true ) {
        if(strlen($uid)==0){
        $sqlQuery="SELECT * FROM members WHERE  pri_email='$eid'";
        //echo $sqlQuery;
        $result=mysqli_query($CCIHCon,$sqlQuery)or die(mysqli_error($CCIHCon));//die("Unable connect to the table");
        if( mysqli_num_rows($result) > 0){
            $error="This email id is already registered. Please provide non-existing id  "."<br/>";           
        }
        else{
                $sqlQuery1="Insert into members(center_id,center_name,name,designation,pri_email,off_address,mobile1,fax,previlege,suspended) values ('$centreName[0]','$centreName[1]','$uname','$Design','$eid','$uadd','$ucontact','$ufax','$prev','$sacc') ";
                $result1=mysqli_query($CCIHCon,$sqlQuery1)or die(mysqli_error($CCIHCon));//die("Unable connect to the table");
                if($result1)
                    $msg="Successful! The new password link was sent to the registered email id";
                  sendEmail($eid);  
        }

    }
    else
    {
        $sqlQuery1="update members set center_id='$centreName[0]',center_name='$centreName[1]', name='$uname', designation='$Design', pri_email='$eid', off_address='$uadd', mobile1='$ucontact', fax='$ufax', previlege='$prev', suspended='$sacc' where uid='$uid' ";
        $result1=mysqli_query($CCIHCon,$sqlQuery1)or die(mysqli_error($CCIHCon));//die("Unable connect to the table");
                if($result1)
                    $msg="The details has been updated successfully!";
    }
}
}
function sendEmail($eid){
    $tran_link=constant("WEB_DOMAIN").'/chpwd.php?d='. bin2hex(strip_tags($eid));
    //$tran_link='http://localhost/chpwd.php?d='. strip_tags($eid);
     //mail starts here
     $to = strip_tags($eid) ;
     $subject = '30x30 Health Systems Initiative Password Reset';

     $headers = "From:  30x30@ccih.org \r\n";
     
     $headers .= "MIME-Version: 1.0\r\n";
     $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

     $message = '<html><body>';
     $message .= '[This message was automatically generated by 30x30 Health Systems Initiative portal]';
     $message .= '<p>Click the link below to set your new password and log in.</p><br/>';
     $message .= "<p><a href=$tran_link target='_blank'>Set your new password</a></p>";
     
     //mail($to, $subject, $message, $headers); //--Actual mail sender
    // $msg="A password reset link was sent. Click the link in the email to reset a new password. If you do not receive an email within 5 minutes, please click the re-send email link below..";

//Send grid Function -Start
$email = new \SendGrid\Mail\Mail();
$email->setFrom("30x30@ccih.org", "30x30 Health Systems Initiative");
$email->setSubject($subject);
$email->addTo($to);
$email->addContent("text/html", $message);

$sendgrid = new \SendGrid(SENDGRID_API_KEY);
$response = $sendgrid->send($email);

//Send grid Function -End

}
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Fav Icon  -->
    <!-- <link rel="shortcut icon" href="./images/favicon.png"> -->
    <!-- Page Title  -->
    <title>30x30 Health Systems Initiative </title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="./assets/css/style.css">
    <style>
input[type=number] {
    -webkit-appearance: textfield;
    -moz-appearance: textfield;
    appearance: textfield;
}
.btn-radus{
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
        </style>
</head>

<body class="ccih-body bg-white npc-default has-aside ">
    <div class="ccih-app-root">
        <!-- main header-->
        <div class="ccih-main ">
            <!-- wrap -->
            <div class="ccih-wrap ">
                <?include("header.php");  ?>
                <!-- main header -->
                <!-- content  -->
                <div class="ccih-content ">
                    <div class="container wide-xl">
                        <!-- .ccih-aside -->
                        <div class="ccih-content-body">
                            <div class="ccih-content-wrap">
                            <div class="components-preview wide-md mx-auto">
                                <div class="alert alert-bi-file bg-primary text-white mb-0 rounded-0">
                                    <div class="ccih-block-head ccih-block-head-lg ">
                                        <div class="ccih-block-head-content">
                                            <h4 class="ccih-block-title fw-normal"><em class="icon ni ni-list-index"></em> User details</h4>
                                        </div>
                                    </div>
                                </div>
                                
                                    <!-- .ccih-block-head -->
                                    <form method="post" action="<?echo $_SERVER['PHP_SELF'] ?>" autocomplete="off" class="form-validate">
                                    <div class="ccih-block ccih-block-lg">
                                        <div class="card card-preview rounded-0">
                                            <div class="card-inner ">
                                            <?
                                                if($error){
                                                echo "<div class='alert alert-fill alert-danger alert-icon'>";
                                                echo '<em class="icon ni ni-cross-circle"></em> '.$error;
                                                echo "</div>";
                                                }
                                                if($msg){
                                                    echo "<div class='alert alert-fill alert-success alert-icon'>";
                                                    echo '<em class="icon ni ni-check"></em> '.$msg;
                                                    echo "</div>";
                                                    }
                                                ?>
                                            <ul class="nav nav-tabs mt-n3 ">
                                                        <li class="nav-item">
                                                            <a class="nav-link active" data-toggle="tab" href="#cenDetails"><em class="icon ni ni-bookmark"></em><span>Create/Update User</span></a>
                                                        </li>
                                                        <li class="nav-item">
                                                            <a class="nav-link" data-toggle="tab" href="#ViewCent"><em class="icon ni ni-view-row-fill"></em><span>View Users</span></a>
                                                        </li>
                                                    </ul>
                                                    <div class="tab-content">
                                                        <div class="tab-pane active" id="cenDetails">
                                                        <!--  -->
                                                    <div class="alert alert-light mt-2">
                                                    <input type="hidden" class="form-control" id="uid" name="uid" readonly value='<?if(strlen($uid)!=0) echo $uid; else echo $rsmember['uid'];?>'>
                                                   <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Name</label>
                                                            <div class="form-control-wrap">
                                                                <input type="text" class="form-control" id="uname" name="uname" required value='<?if(strlen($uname)!=0) echo $uname; else echo $rsmember['name'];?>'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Designation</label>
                                                            <div class="form-control-wrap">
                                                                <input type="text" class="form-control" id="Design" name="Design" value='<?if(strlen($Design)!=0) echo $Design; else echo $rsmember['designation'];?>'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Centre name</label>
                                                            <div class="form-control-wrap">
                                                            <select class="form-select form-control form-control-lg" data-search="on" name="centreName" required>
                                                                <option value="">Select Centre</option>
                                                                <option value='999' "<?if($rsmember['center_id']==999) {echo " selected =\"true\"";}?>"> CCIH-Superuser</option>"."<BR>"
                                                                <? 
																 $sqlQuery11="SELECT center_name,cid FROM center_details where dropout=0  order by center_name";
																		  $result3=mysqli_query($CCIHCon,$sqlQuery11)or die("Unable connect to the table");

																		  while($valu3=mysqli_fetch_array($result3))
																 {
                                                                     $dctxt=$valu3['cid'].'-'.$valu3['center_name'];
                                                                     //echo "<script>console.log('Debug Objects: " . $dctxt . "' );</script>";
                                                                     
                                                                     $pctxt=$rsmember['center_id'].'-'.$rsmember['center_name'];
                                                                     ?>
																		  <option value='<?=$dctxt?>' "<?if($dctxt==$pctxt) {echo " selected =\"true\"";}?>" > <?=$valu3['center_name']?></option>"."<BR>"
																<?
                                                                }     
																 ?>
                                                            </select>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Email ID</label>
                                                            <div class="form-control-wrap">
                                                                <input type="email" class="form-control" id="eid" name="eid" required value='<?if(strlen($eid)!=0) echo $eid; else echo $rsmember['pri_email'];?>'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Address</label>
                                                            <div class="form-control-wrap">
                                                                <textarea class="form-control" name="uadd"><?if(strlen($uadd)!=0) echo $uadd; else echo $rsmember['off_address'];?></textarea>
                                                            </div>
                                                        </div>
                                                        </div>
                                                        <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Contact no's</label>
                                                            <div class="form-control-wrap">
                                                                <input type="text" class="form-control" id="ucontact" name="ucontact" value='<?if(strlen($ucontact)!=0) echo $ucontact; else echo $rsmember['mobile1'];?>'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label" for="default-03">Fax</label>
                                                            <div class="form-control-wrap">
                                                                <input type="text" class="form-control" id="ufax" name="ufax" value='<?if(strlen($ufax)!=0) echo $ufax; else echo $rsmember['fax'];?>'>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label">Previlege</label>
                                                            <ul class="custom-control-group g-3 align-center">
                                                                <li>
                                                                    <div class="custom-control custom-radio">
                                                                        <input type="radio" class="custom-control-input" value="OA" name="prev" id="fstat1" required "<?php  if ($rsmember['previlege']=="OA" || $prev=="OA") {echo " checked =\"yes\"";} ?>">
                                                                        <label class="custom-control-label" for="fstat1">Organization Admin</label>
                                                                    </div>
                                                                </li>
                                                                <li>
                                                                    <div class="custom-control custom-radio">
                                                                        <input type="radio" class="custom-control-input" value="SA" name="prev" id="fstat2" required "<?php  if ($rsmember['previlege']=="SA" || $prev=="SA") {echo " checked =\"yes\"";} ?>">
                                                                        <label class="custom-control-label" for="fstat2">Super Admin</label>
                                                                    </div>
                                                                </li>                                                                       
                                                            </ul>
                                                        </div>
                                                            </div>
                                                            <div class="col-md-12 mb-3">
                                                        <div class="form-group">
                                                            <label class="form-label">Suspend Account</label>
                                                            <ul class="custom-control-group g-3 align-center">
                                                                <li>
                                                                    <div class="custom-control custom-radio">
                                                                        <input type="radio" class="custom-control-input" value="1" name="sacc" id="fstat11" required "<?php  if ($rsmember['suspended']=="1" || $sacc=="1") {echo " checked =\"yes\"";} ?>">
                                                                        <label class="custom-control-label" for="fstat11">Yes</label>
                                                                    </div>
                                                                </li>
                                                                <li>
                                                                    <div class="custom-control custom-radio">
                                                                        <input type="radio" class="custom-control-input" value="0" name="sacc" id="fstat21" required "<?php  if ($rsmember['suspended']=="0" || $sacc=="0") {echo " checked =\"yes\"";} ?>">
                                                                        <label class="custom-control-label" for="fstat21">No</label>
                                                                    </div>
                                                                </li>                                                                       
                                                            </ul>
                                                        </div>
                                                            </div>
                                                    <hr class="preview-hr mb-2 mt-5 ">
                                                    <div class="col-sm-12 mb-3 row">                                                    
                                                        <div class="form-group text-left col-sm-4">
                                                            <div class="form-control-wrap">
                                                            <?if(strlen($_GET['e'])!=0){?>
                                                            <button type="submit" name="resetpwd" class="btn btn-lg btn-secondary">Reset this user password</button>
                                                            <?}?>
                                                            </div>
                                                        </div>
                                                        <div class="form-group text-right col-sm-8">
                                                            <div class="form-control-wrap">
                                                            <button type="submit" name="sub" class="btn btn-lg btn-primary">Save Informations</button>
                                                            <a class="btn btn-lg btn-danger text-white" href="ahome.php" >Exit</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                 

                                                    </div>
                                                    <!--  -->
                                                        </div>
                                                        <div class="tab-pane" id="ViewCent">
                                                        <table class="datatable-init table">
                                                        <thead>
                                                            <tr>
                                                                <th>Name</th>
                                                                <th>Designation</th>
                                                                <th>Center</th>                                                                
                                                                <th>Email</th>
                                                                <th>Edit</th>
                                                                <th>Delete</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                         <?
                                                            $sqlQuery="SELECT * FROM members where previlege in('SA','OA')  ";  
                                                             $pickQuery=mysqli_query($CCIHCon,$sqlQuery)or die("Unable connect to the table");
                                                             while ($listdata=mysqli_fetch_array($pickQuery)){
                                                         ?>
                                                            <tr>
                                                                <td><?=$listdata['name'];?></td>
                                                                <td><?=$listdata['designation'];?></td>
                                                                <td><?=$listdata['center_name'];?></td>
                                                                <td><?=$listdata['pri_email'];?></td>
                                                                <td class="text-center"><a href="adm_user_det.php?e=<?=$listdata['uid'];?>" ><em class="icon ni ni-edit h6"></em></a></td>
                                                                <td class="text-center"><a href="adm_user_det.php?d=<?=$listdata['uid'];?>" ><em class="icon ni ni-trash-alt h6"></em></a></td>
                                                            </tr>
                                                            <? } ?>
                                                
                                                        </tbody>
                                                        </table>
                                                        </div>
                                                    </div>
                                                    <!--  -->
                                                    </div> <!-- card inner -->
                                            </div>
                                            <div class="alert alert-bi-file bg-gray-200  rounded-0"></div>


                                        </div>
                                    </form>
                                    </div>
                                </div>

                            


                        </div>
                    </div>
                </div>
            </div>
            <!-- content  -->
        </div>
        <!-- wrap  -->
    </div>
    <!-- main  -->
    </div>
    <!-- JavaScript -->
    <script src="./assets/js/bundle.js"></script>
    <script src="./assets/js/scripts.js"></script>
    <script>
$("#form1").validate({
    rules:{         

        q1_1:{
            digits:true,  
            min:0,
            // max:300,            
        },
        q1_2:{
            digits:true,  
            min:0,
            // max:250000,             
        },
        q1_3:{
            digits:true,  
            min:0,
            // max:100,             
        },
        q2_1:{
            digits:true, 
            min:0,
            // max:1000000,              
        },            
        q2_2:{
            digits:true,  
            min:0,
            // max:100,             
        },
        q2_3:{
            digits:true, 
            min:0,
            // max:1000000,              
        },            
        q3_1:{
            digits:true,  
            min:0,
            // max:100,             
        }
        
        
    },
messages: {},
highlight:function (element) {
    $(element)
            .closest('.form-group').removeClass('has-success').addClass('has-error');
},

unhighlight:function (element) {
    $(element)
            .closest('.form-group').removeClass('has-error');
}

});


   </script>
</body>

</html>