<?
require("config.php");
require('vendor/autoload.php');
$today1 = date("F j, Y, g:i:s a");

if(isset($_POST['sub']))
   {
$emailid=$_POST["emailid"];

if(strlen($emailid)==0 )
   	{
   	$error=$error. "Enter your email address"."<br />";
    $errval=true;
    }
	
	if($error!=TRUE)
	{
	$flaa = mysqli_query($CCIHCon, "select * from members where pri_email='$emailid'") or die(mysqli_error($CCIHCon));
	
	if (mysqli_num_rows($flaa) >0){
		$rsmember = mysqli_fetch_array($flaa);
		
			 
		if($rsmember['suspended']!=1){
        $name = $rsmember['name'];
        $pri_email = $rsmember['pri_email'];
		$center_id = $rsmember['center_id'];
        $tran_link=constant("WEB_DOMAIN").'/chpwd.php?d='. bin2hex(strip_tags($rsmember['pri_email']));
        //$tran_link='http://localhost/chpwd.php?d='. bin2hex(strip_tags($rsmember['pri_email']));
        //mail starts here
        $to = strip_tags($pri_email) ;
        $subject = '30x30 Health Systems Initiative Password Reset';

        $headers = "From:  30x30@ccih.org \r\n";
        
        $headers .= "MIME-Version: 1.0\r\n";
        $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

        $message = '<html><body>';
        $message .= '[This message was automatically generated by 30x30 Health Systems Initiative portal]';
        $message .= '<p>Click the link below to set your new password and log in.</p><br/>';
        $message .= "<p><a href=$tran_link target='_blank'>Set your new password</a></p>";
        
        //mail($to, $subject, $message, $headers); //--old method send mails
            //Send grid Function -Start
            $email = new \SendGrid\Mail\Mail();
            $email->setFrom("30x30@ccih.org", "30x30 Health Systems Initiative");
            $email->setSubject($subject);
            $email->addTo($to);
            $email->addContent("text/html", $message);

            $sendgrid = new \SendGrid(SENDGRID_API_KEY);
            $response = $sendgrid->send($email);

            //Send grid Function -End

        $msg="A password reset link was sent. Click the link in the email to reset a new password. If you do not receive an email within 5 minutes, please click the re-send email link below..";
//Mail ends
    }else{
		$error="Your account is disabled";	
		}
		
	
	}
	else{
	$error="Your Email ID not registered with us. Please check!";
	}
         				
	
	
	}
}


?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Page Title  -->
    <title>30x30 Health Systems Initiative </title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="./assets/css/style.css">
</head>

<body class="ccih-body bg-white npc-default pg-auth">
    <div class="ccih-app-root">
        <!-- main  -->
        <div class="ccih-main ">
            <!-- wrap -->
            <div class="ccih-wrap ccih-wrap-nosidebar">
                <!-- content -->
                <div class="ccih-content ">
                    <div class="ccih-split ccih-split-page ccih-split-md">                    
                        <!-- .ccih-split-content -->
                        <div class="ccih-split-content ccih-split-stretch bg-bluectm d-flex" >
                        <!-- <div class="ccih-split-content ccih-split-stretch bg-bluectm d-flex toggle-break-lg toggle-slide toggle-slide-right" data-content="athPromo" data-toggle-screen="lg" data-toggle-overlay="true"> -->
                        <div class="slider-wrap w-100 w-max-550px p-3 p-sm-5 m-auto">                        
                                <div class="slider-item">                                
                                    <div class="ccih-feature ccih-feature-center">   
                                        <div class="ccih-feature-img">                                            
                                            <img class="round" src="./images/_30x30_logo-lg.png" srcset="./images/_30x30_logo-lg.png 2x" alt="">
                                            <!-- <img class="round" src="./images/_30x30_logo-lg-White.png" srcset="./images/_30x30_logo-lg-White.png 2x" alt=""> -->
                                            <!-- <img class="round" src="./images/_30x30_logo-lg-Yellow.png" srcset="./images/_30x30_logo-lg-Yellow.png 2x" alt=""> -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- .slider-wrap -->
                        </div>
                        <!-- .ccih-split-content -->


                        <div class="ccih-split-content ccih-block-area ccih-block-area-column ccih-auth-container bg-white tm-30">
                          
                        <!-- <div class="absolute-top-right d-lg-none p-3 p-sm-5">
                                <a href="#" class="toggle btn-white btn btn-icon btn-light" data-target="athPromo"><em class="icon ni ni-info"></em></a>
                            </div> -->
                            <div class="ccih-block ccih-block-middle ccih-auth-body ">
                                <div class="ccih-block-head mt-5">
                                    <div class="ccih-block-head-content">
                                        <h5 class="ccih-block-title">Recovery your Account</h5>
                                        <div class="ccih-block-des">
                                            <p>Please enter your email address to search for your 30x30 Health Systems Initiative portal account.</p>
                                        </div>
                                    </div>
                                </div>
                                <!-- .ccih-block-head -->
                                <form method="post" action="<?echo $_SERVER['PHP_SELF'] ?>" autocomplete="off" class="form-validate">
                                 <?
                                    if($error){
                                    echo "<div class='alert alert-fill alert-danger alert-icon'>";
                                    echo '<em class="icon ni ni-cross-circle"></em> '.$error;
                                    echo "</div>";
                                    }
                                    if($msg){
                                        echo "<div class='alert alert-fill alert-success alert-icon'>";
                                        echo '<em class="icon ni ni-check"></em> '.$msg;
                                        echo "</div>";
                                        }
                                    ?>
                                    <div class="form-group">
                                        <div class="form-label-group ">
                                            <label class="form-label" for="default-01">Email</label>
                                        </div>
                                        <input type="email" class="form-control form-control-lg" name="emailid" placeholder="Enter your email address" required>
                                    </div>
                                    <!-- .foem-group -->
                                    
                                    <div class="form-group">
                                        <button class="btn btn-lg btn-primary btn-block" type="submit" name="sub" >Search</button>
                                    </div>
                                </form>
                                <!-- form -->
                                <div class="form-note-s2 pt-4"> Or return to  <a href="index.php">Sign In</a> page
                                </div>


                            </div>
                            <!-- .ccih-block -->
                            <div class="ccih-block ccih-auth-footer">
                                <div class="mt-3 text-right">
                                    <p>&copy; <?=date("Y"); ?> CCIH. All Rights Reserved.</p>
                                </div>
                            </div>
                            <!-- .ccih-block -->
                        </div>



                    </div>
                    <!-- .ccih-split -->
                </div>
                <!-- wrap -->
            </div>
            <!-- content -->
        </div>
        <!-- main-->
    </div>
    <script src="./assets/js/bundle.js"></script>
    <script src="./assets/js/scripts.js"></script>

</html>